# -*- coding: utf-8 -*-
"""final mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ITIGr5TPuJ-3g0nC2BypL6_T5n0AjM3
"""

from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
import torch
from PIL import Image
import gradio as gr



model_name = "nlpconnect/vit-gpt2-image-captioning"
print("Loading model...")
model = VisionEncoderDecoderModel.from_pretrained(model_name)
feature_extractor = ViTImageProcessor.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"Model ready on {device}")

def generate_caption(image):
    if image is None:
        return "Please upload an image first."
    image = image.convert("RGB")
    pixel_values = feature_extractor(images=image, return_tensors="pt").pixel_values
    pixel_values = pixel_values.to(device)

    gen_kwargs = {"max_length": 16, "num_beams": 4}
    output_ids = model.generate(pixel_values, **gen_kwargs)
    caption = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    return caption.strip()

title = "🖼️ AI Image Caption Generator"
description = "Upload any image and the model will describe it in natural language."

demo = gr.Interface(
    fn=generate_caption,
    inputs=gr.Image(type="pil", label="Upload Image"),
    outputs=gr.Textbox(label="Generated Caption"),
    title=title,
    description=description,
)


demo.launch(debug=True)

